version: "2.11"

services:
  db:
     image: mariadb:latest
     environment:
       - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}

     volumes:
       - my-data:/var/lib/mysql
 
  main:
      image: apache/openmeetings:${OM_TAG}
      restart: always
      ports:
        - 5443:5443
        - 8888:8888
      environment:
        - OM_DB_HOST=db
        - OM_RURENTO_WS_URL="ws://localhost:8888/kurento"
        - OM_DB_USER=${MYSQL_USER}
        - OM_DB_PASS=${MYSQL_PASSWORD} 
      volumes:
        - my-meeting:/opt/openmeetings
  
volumes:
    my-data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/user/meeting/volume
    my-meeting:
       driver: local
       driver_opts:
          type: none
          o: bind
          device: /home/user/meeting/mt  
networks:
   meeting_vlan:
        name: meeting_vlan
        driver: macvlan
        driver_opts:
           parent: enp0s3
        ipam:
           config:
             - subnet: 10.0.2.0/24
               gateway: 10.0.2.2
